config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails

  get "delete_cocktails/:id", to: "cocktails#destroy", as: :destroy_cocktail
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, uniqueness: true, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/models/tea.rb
class Tea < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new(set_params)
  end

  def create
    @cocktail = Cocktail.new(set_params)
    if @cocktail.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(set_params)
    if @cocktail.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def set_params
    params.require(:cocktail).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for Cocktail.new do |f| %>
  <%= f.error_notification %>
  <div class="new-tea">
    <%= f.input :name,
                required: true,
                label: "Name"
                %>

    <%= f.input      :doses,
                      collection: [['A squeeze'], ['1 bag'], ['1 stick'], ['A pinch'], ['1 slice']],
                      label: "Select a dose:",
                      :wrapper_html => { :class => "left-field" }
                       %>

    <%= f.association :ingredients,
                      label: "Select an ingredient:",
                      :wrapper_html => { :class => "right-field select2" }
                      %>

    <%= f.input       :doses,
                       collection: [['A squeeze'], ['1 bag'], ['1 stick'], ['A pinch'], ['1 slice']],
                      required: false,
                      label: "Select a dose:",
                      :wrapper_html => { :class => "left-field" }
                           %>

    <%= f.association :ingredients,
                      label: "Select an ingredient:",
                      required: false,
                      :wrapper_html => { :class => "right-field select2" }
                      %>

    <%= f.button :submit,
                  "Add my tea!"
                  %>

  </div>


<% end %>

app/views/cocktails/index.html.erb
<div class="outside-wrapper">
  <div class="inside-container">
    <div class="page-header">
      <h1>Tell me what you Tea</h1>
      <p>Find all your favourite teas in one place</p>

      <div class="tea-cards">
        <div class="row">
        <% @cocktails.each do |cocktail| %>
          <div class="col-xs-12 col-sm-4">
            <div class="card">
              <%= cocktail.name %>
              <%= link_to edit_cocktail_path(cocktail) do %>
              <i class="far fa-edit edit-icon"></i>
              <% end %>
              <%= link_to destroy_cocktail_path(cocktail) do %>
              <i class="far fa-trash-alt delete-icon"></i>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <!---- div closing page-header ---->
    </div>


    <div class="create-tea">
      <div class="page-header">
        <h1> Create your own tea!</h1>
        <%= render 'form' %>
      </div>
    </div>
  <!---- div closing the inside container ---->
  </div>
<!---- div closing the outside wrapper ---->
</div>

app/views/cocktails/new.html.erb
<h1>Create your own tea!</h1>

<%= simple_form_for @cocktail do |f| %>

  <div class="new-tea">
    <%= f.input :name,
                required: true,
                label: "Name"
    %>

    <%= f.association :doses %>

  </div>


<% end %>

app/views/cocktails/show.html.erb
<h1>Cocktails#show</h1>
<p>Find me in app/views/cocktails/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tell me what you tea</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>

</html>